### DISCUSSION TITLE
How to start

### DISCUSSION THREAD

**Discussion by Julien4135** [tillsteinbach/VWsFriend#87] [Q&A]
Hello, I would like to use the project for my car ID.3. I already have a project running on my raspberry with the IDDataLogger program.

I managed to install Docker and Docker composed in the first part of your project with all the dependencies.
Until then everything is fine.

I would like some help for the rest please, I don't know what to do exactly with the two files docker-compose.yml and .env?

In the .env file I must normally fill in my personal data such as my WeConnect address and password and the Admin codes for access to the http; // page
I don't know where to transfer my myconfig.env file to docker? to then run the command: docker-compose --env-file ./myconfig.env up?

Thank you very much for your project, I hope to succeed in putting it into action one day.

**Comment by tillsteinbach** [comment]
You just need to transfer both files to your raspberry and then execute the command in the folder where the files are.

**Reply by Julien4135** [reply]
Thanks for your answer, I just understood, but the concern is that docker in my raspberry is under the IDDataLogger folder, so it's either one or the other?
![dock](https://user-images.githubusercontent.com/93113346/138647326-9023834b-2f16-46d0-b590-3807c9c6013d.png)

**Reply by tillsteinbach** [reply]
I think you are mixing things up here. Your IDDataLogger folder just has a folder named docker. But this has nothing to do with VWsFriend.
For VWsFriend you can just select a folder anywhere and put the files there.

**Reply by Julien4135** [reply]
Hello, can you still help me please? apparently it works fine at the start of the load and at the end I have an error ?
[nouveau 1.txt](https://github.com/tillsteinbach/VWsFriend/files/7413809/nouveau.1.txt)

**Reply by tillsteinbach** [reply]
Ah, this looks like a problem for docker on raspberry pi. I have reports that this is helping:

```
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 04EE7237B7D453EC 648ACFD622F3D138
echo "deb http://deb.debian.org/debian buster-backports main" | sudo tee -a /etc/apt/sources.list.d/buster-backports.list
sudo apt update
sudo apt install -t buster-backports libseccomp2
```

**Reply by Julien4135** [reply]
Hello and thank you again for your help, it's nice to see people like you in this community!
I managed to move forward a bit, mail it now seems to have a probably connection with the cloud?

Thanks for your patience with me.
[nouveau2.txt](https://github.com/tillsteinbach/VWsFriend/files/7415765/nouveau2.txt)

**Comment by tillsteinbach** [comment]
Strange. It somehow does not find your database. Can you delete all volumes again and try to recreate?
```
docker-compose down -v
docker-compose --env-file ./myconfig.env up
```
**WARNING: Use this command with care. It deletes your already recorded data!**

**Reply by Julien4135** [reply]
Ok it's in progress, I'll keep you posted.

**Reply by Julien4135** [reply]
This is what is happening now
[nouveau3.txt](https://github.com/tillsteinbach/VWsFriend/files/7416048/nouveau3.txt)

**Reply by tillsteinbach** [reply]
You set an interval lower than 300 if you set the interval back to 300 it should work:
`WECONNECT_INTERVAL=300`

**Reply by tillsteinbach** [reply]
ahh sorry, no my command was wrong!

```
docker-compose down -v
docker-compose --env-file ./myconfig.env up
```
**WARNING: Use this command with care. It deletes your already recorded data!**

**Reply by Julien4135** [reply]
I finally manage to connect with my ip 192.168.X.X: 3000 with my credentials register in myconfig.env
but there is still a problem, but I do not know if everything is normal or not for the moment at this stage of the project?

Yes I think I made a mistake
[nouveau4.txt](https://github.com/tillsteinbach/VWsFriend/files/7416240/nouveau4.txt)
![graf](https://user-images.githubusercontent.com/93113346/138834581-cab86a9a-a0f1-40a8-b598-639a0598f268.png)

**Reply by tillsteinbach** [reply]
It looks like you made changes to the docker-compose.yml (Creating network "pi_backend" with the default driver) can you paste the changed docker-compose.yml here?

**Reply by Julien4135** [reply]
`version: '3.8'
services:
  vwsfriend:
    image: tillsteinbach/vwsfriend:${VWSFRIEND_VERSION-latest}
    ports:
     - 4000:4000
    networks:
      backend:
    volumes:
      - vwsfriend_data:/config
    environment:
      - WECONNECT_USER
      - WECONNECT_PASSWORD
      - WECONNECT_INTERVAL
      - DATABASE_URL=postgresql://${DB_USER-admin}:${DB_PASSWORD-secret}@postgresdbbackend/vwsfriend
      - ADDITIONAL_PARAMETERS=--with-database --with-abrp -vv
    depends_on:
      postgresdb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: (wget -qO- http://localhost:4000/healthcheck | grep "ok" -q) || exit 1
      interval: 60s
      timeout: 10s
      retries: 3

  postgresdb:
    image: postgres:13
    networks:
      backend:
        aliases:
          - postgresdbbackend
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    user: postgres
    environment:
      - POSTGRES_USER=${DB_USER-admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD-secret}
      - POSTGRES_DB=vwsfriend
      - TZ=UTC
      - PGTZ=UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=${DB_USER-admin} --dbname=vwsfriend"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: tillsteinbach/vwsfriend-grafana:${VWSFRIEND_GRAFANA_VERSION-latest}
    ports:
      - 3000:3000
    networks:
      bridge:
      backend:
        aliases:
          - grafanabackend
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${USERNAME-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${PASSWORD-secret}
      - DB_USER=${DB_USER-admin}
      - DB_PASSWORD=${DB_PASSWORD-secret}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "(wget -qO- http://localhost:3000/api/health | grep '\"database\": \"ok\"' -q) || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3

networks:
  bridge:
  backend:

volumes:
  vwsfriend_data:
  postgresdb_data:
  grafana_data:`

**Reply by tillsteinbach** [reply]
hmmm, this looks good. Right now I have no idea why the database cannot be reached from the container.

**Reply by Julien4135** [reply]
`in` the myconfig.env file:
I have moficier like that
and I am not using the pin code
[nouveau5.txt](https://github.com/tillsteinbach/VWsFriend/files/7416505/nouveau5.txt)

**Reply by tillsteinbach** [reply]
Do you have maybe fancy characters in the DB_USER or DB_PASSWORD?

**Reply by Julien4135** [reply]
just @

**Reply by tillsteinbach** [reply]
Can you try a user/password without @?

**Reply by Julien4135** [reply]
Yes I can but I take care of it tonight, I have to go to work.
Can you give me the command lines back to erase everything and start over with blank docker?
I would modify the myconfig.env file without @

**Reply by tillsteinbach** [reply]
`docker rm -f $(docker ps -a -q)` will delete all containers
`docker volume rm $(docker volume ls -q)` will delete all persistent volumes

**Reply by Julien4135** [reply]
Hello everything seems to work, I have some data displayed, I downloaded the file  https://github.com/tillsteinbach/VWsFriend/blob/main/docker-compose-homekit-host.yml and run the command docker-compose -f docker-compose-homekit-host.yml
On the other hand, I don't know how I found my car in homekit? 

![Capture](https://user-images.githubusercontent.com/93113346/139011337-72535329-720b-4101-8ef8-b7a57c544219.PNG)
![gra](https://user-images.githubusercontent.com/93113346/139011354-b90cf378-bd4e-45e5-9bf5-5c17b6567d32.png)

**Reply by tillsteinbach** [reply]
You should have a link in the UI. There you find a QR code that you scan with the Home app to add VWsFriend as a new bridge.
<img width="1982" alt="Bildschirmfoto 2021-09-20 um 18 39 28 Kopie" src="https://user-images.githubusercontent.com/3825852/139013868-962fe779-55ee-4f3f-b4e1-6b212e915864.png">

**Reply by Julien4135** [reply]
ok but then suddenly, I do not yet have the link on the page http: //  
[nouveau6.txt](https://github.com/tillsteinbach/VWsFriend/files/7424139/nouveau6.txt)
![image](https://user-images.githubusercontent.com/93113346/139015265-f3d3cd9a-6d8e-403d-b239-4523c8f3ea1d.png)

**Reply by tillsteinbach** [reply]
If the link is not there you are probably not using a docker-compose file with HomeKit.
```
docker-compose -f docker-compose-homekit-host.yml --env-file ./myconfig.env up
```

**Reply by Julien4135** [reply]
When launching the command I got this error : 

`pi@raspberrypi:~ $ docker-compose -f docker-compose-homekit-host.yml --env-file ./myconfig.env up
Recreating pi_postgresdb_1 ...
pi_grafana_1 is up-to-date
Recreating pi_postgresdb_1 ... error

ERROR: for pi_postgresdb_1  Cannot start service postgresdb: driver failed programming external connectivity on endpoint pi_postgresdb_1 (91eb591a53bba6f01ab2ee1a00f07e8f1fc5f374e6107382f96cc69fa5303149): Error starting userland proxy: listen tcp4 0.0.0.0:5432: bind: address already in use

ERROR: for postgresdb  Cannot start service postgresdb: driver failed programming external connectivity on endpoint pi_postgresdb_1 (91eb591a53bba6f01ab2ee1a00f07e8f1fc5f374e6107382f96cc69fa5303149): Error starting userland proxy: listen tcp4 0.0.0.0:5432: bind: address already in use
ERROR: Encountered errors while bringing up the project.`

**Reply by tillsteinbach** [reply]
I can think of two possibilities: Either there is another application using the port 5432 on your Pi or you still have a postgresdb docker running from your previous try that is blocking the port

**Reply by Julien4135** [reply]
I lean more for the second solution, the only application that runs in parallel, is IDDataLogger, which seems to be working well so far despite all the changes made since the start of the project.

Maybe there is a way to find out? I do not know ?

**Reply by tillsteinbach** [reply]
`docker container ls -a` should show you everything what is running.
`sudo lsof -i:5432` should show you the process that has the port open

**Reply by Julien4135** [reply]
So I went back to the initial configuration like this morning when it worked without HomeKit  👍

pi@raspberrypi:~ $ docker container ls -a
CONTAINER ID   IMAGE                                    COMMAND                  CREATED         STATUS                   PORTS                                       NAMES
13da9504730d   tillsteinbach/vwsfriend:latest           "/bin/sh -c 'vwsfrie…"   7 minutes ago   Up 6 minutes (healthy)   0.0.0.0:4000->4000/tcp, :::4000->4000/tcp   pi_vwsfriend_1
8a27315b3b7d   tillsteinbach/vwsfriend-grafana:latest   "/run.sh"                8 minutes ago   Up 8 minutes (healthy)   0.0.0.0:3000->3000/tcp, :::3000->3000/tcp   pi_grafana_1
27de987f1d8e   postgres:13                              "docker-entrypoint.s…"   8 minutes ago   Up 8 minutes (healthy)   5432/tcp                                    pi_postgresdb_1
pi@raspberrypi:~ $ sudo lsof -i:5432
COMMAND  PID     USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
postgres 623 postgres    3u  IPv6  19008      0t0  TCP localhost:postgresql (LISTEN)
postgres 623 postgres    5u  IPv4  19011      0t0  TCP localhost:postgresql (LISTEN)
php      820       pi    3u  IPv6  22684      0t0  TCP localhost:51042->localhost:postgresql (ESTABLISHED)
postgres 884 postgres   10u  IPv6  22685      0t0  TCP localhost:postgresql->localhost:51042 (ESTABLISHED)
pi@raspberrypi:~ $

**Reply by tillsteinbach** [reply]
so without HomeKit it works and with you have the problem?

**Reply by Julien4135** [reply]
Yes that's it

**Reply by tillsteinbach** [reply]
Ah, I just had a look here: https://github.com/robske110/IDDataLogger/blob/master/docker/docker-compose.yml Your IDDataLogger is also coming with a Postgres Database. There is your conflict. So either you use the same database for both, or you change the port of one of the databases to something different than 5432

**Reply by Julien4135** [reply]
Ok I understand, but I do not know what solution to take suddenly? the ideal would be maybe to change the port of VWsFriend if possible so that it is no longer in conflict with IDDataLogger?

**Reply by tillsteinbach** [reply]
I can make the port configurable. But I will probably not have time for that anymore this week.

**Reply by Julien4135** [reply]
Ok no problem, I can wait. We try to solve the problem later. I look forward to hearing from you later.
Good evening to you

**Reply by tillsteinbach** [reply]
Ok, I didn't want to let you down. Can you try the latest release with this docker-compose:
```
version: '3.8'
services:
  vwsfriend:
    image: tillsteinbach/vwsfriend:${VWSFRIEND_VERSION-latest}
    network_mode: host
    extra_hosts:
      - "postgresdbbackend:127.0.0.1"
      - "postgresdb:127.0.0.1"
      - "grafanabackend:127.0.0.1"
      - "grafana:127.0.0.1"
    volumes:
      - vwsfriend_data:/config
    environment:
      - WECONNECT_USER
      - WECONNECT_PASSWORD
      - WECONNECT_INTERVAL
      - DATABASE_URL=postgresql://${DB_USER-admin}:${DB_PASSWORD-secret}@${DB_HOSTNAME-postgresdbbackend}:${DB_PORT-5432}/${DB_NAME-vwsfriend}
      - ADDITIONAL_PARAMETERS=--with-database --with-abrp --with-homekit -vv
    depends_on:
      postgresdb:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: (wget -qO- http://localhost:4000/healthcheck | grep "ok" -q) || exit 1
      interval: 60s
      timeout: 10s
      retries: 3

  postgresdb:
    image: postgres:13
    ports:
      - ${DB_PORT-5432}:${DB_PORT-5432}
    networks:
      backend:
        aliases:
          - ${DB_HOSTNAME-postgresdbbackend}
    volumes:
      - postgresdb_data:/var/lib/postgresql/data
    user: postgres
    environment:
      - POSTGRES_USER=${DB_USER-admin}
      - POSTGRES_PASSWORD=${DB_PASSWORD-secret}
      - POSTGRES_DB=${DB_NAME-vwsfriend}
      - TZ=UTC
      - PGTZ=UTC
    command: -p ${DB_PORT-5432}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=${DB_USER-admin} --dbname=${DB_NAME-vwsfriend}"]
      interval: 10s
      timeout: 5s
      retries: 5

  grafana:
    image: tillsteinbach/vwsfriend-grafana:${VWSFRIEND_GRAFANA_VERSION-latest}
    ports:
      - ${GF_SERVER_HTTP_PORT-3000}:${GF_SERVER_HTTP_PORT-3000}
    networks:
      bridge:
      backend:
        aliases:
          - grafanabackend
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${USERNAME-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${PASSWORD-secret}
      - GF_SERVER_HTTP_PORT=${GF_SERVER_HTTP_PORT-3000}
      - DB_USER=${DB_USER-admin}
      - DB_PASSWORD=${DB_PASSWORD-secret}
      - DB_HOSTNAME=${DB_HOSTNAME-postgresdbbackend}
      - DB_PORT=${DB_PORT-5432}
      - DB_NAME=${DB_NAME-vwsfriend}
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "(wget -qO- http://localhost:${GF_SERVER_HTTP_PORT-3000}/api/health | grep '\"database\": \"ok\"' -q) || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3

networks:
  bridge:
  backend:

volumes:
  postgresdb_data:
  grafana_data:
  vwsfriend_data:
```
It is important that you do a `docker-compose pull` first to fetch the newest version. With that version you can add `DB_PORT=5433` to your env configuration file. This should move the postgres server to an empty port.
