### ISSUE TITLE
HomeKit PIN not set to value defined in env file

### ISSUE THREAD

**Issue by cmantsch** [tillsteinbach/VWsFriend#46]
The PIN defined in the env file is never used anywhere, therefore a new PIN is generated on every start. 
Is this currently just prepared for future use?

Also the Home App on my iPhone fails to connect to the bridge (running in macvlan mode) but that might be an issue on my side as well.

**Comment by tillsteinbach** [comment]
Ah yes, I forgot to throw the pin out of that template. It is not used anymore as the barcode can now be displayed in the UI.

Regarding the connection issue: you scan the barcode and it does not connect? Does it find the bridge in the mode where you do not scan the barcode?

Usually this happens when there is a problem with multicast. HomeKit relies on multicast to announce the bridge, if that does not work you do not see the bridge.

**Comment by tillsteinbach** [comment]
I removed the PIN from the template

**Comment by cmantsch** [comment]
Thanks for the response!

Yes I scanned the barcode from the Web UI but also tried to manually add it (it shows up in the Home App and prompts for the PIN, but times out after some minutes). Probably this might conflict with my homebridge instance I am running on the same machine in host mode, I might need to find a solution there.

**Comment by tillsteinbach** [comment]
We can try some things.

First of all: to ensure it is not due to the bridge being in some strange state you could delete the VWsFriend volume and try again. You will only loose the ABRP settings (if you have any).

Then it would be interesting if there is maybe a conflict with ports or other resources. I can have a look what the default ports are with homebridge. If that is a problem it should be fairly easy to make those settings adjustable.

What I do is: I run homebridge also with a macvlan network because I don't like host mode. It is a bit unfortunate that this is necessary at all due to the multicast requirements. But Incan say that this is working well.

**Comment by cmantsch** [comment]
I deleted the volume and redeployed the vwsfriend container, but no change there.

I am quite confident in using docker lately, but macvlan is something I always avoided and therefore don't know how exactly those works. Host mode was a quick solution back then when I deployed homebridge.

Are you using a single network for both homebridge and vwsfriend or does each service has its own /32 like in the macvlan compose file (because that didn't work for me due to gateway conflict)?

Homekit is also something that has not that high priority for me, so I might try to figure it out on my own when I find some time.

**Comment by tillsteinbach** [comment]
Yes, the problem is that you cannot have two networks with the same gateway. I don't know why. What I'm doing is, I have this stack:
```
version: '3.8'
services:
  hello_world:
    image: hello-world:latest
    networks:
      global-backend-network:
      global-macvlan-network:
        ipv4_address: 10.11.5.255
networks:
  global-backend-network:
    name: global-backend-network
  global-macvlan-network:
    name: global-macvlan-network
    driver: macvlan
    driver_opts:
      parent: br0
    enable_ipv6: true
    ipam:
      config:
        - subnet: 10.11.0.0/16
          ip_range: 10.11.5.0/24
          gateway: 10.11.2.254
        - subnet: 2003:e3:ff04:b600::/64
```
You need the hello world container because you cannot have only networks in the compose file. 

In Homebridge (and VWsFriend) I then add the network, e.g.
```
    networks:
      global-macvlan-network:
        ipv4_address: 10.11.5.249
        priority: 1000
```
Of course you also need to add it to the networks section:
```
networks:
  global-macvlan-network:
    external: true
```

You would of course need to adapt the parent interface, IP addresses, and masks for your network.
